CREATE PROCEDURE [dbo].[SP_STOCK]
as

MERGE STOCK AS TARGET
USING (select * from stock_stg where CONVERT (date, auctiondatetime) >= CONVERT (date, getdate())) AS SOURCE
ON (TARGET.branchID = SOURCE.branchID AND TARGET.AUCTIONDATETIME = SOURCE.AUCTIONDATETIME 
AND TARGET.STOCKNUMBER= SOURCE.STOCKNUMBER )
WHEN NOT MATCHED BY TARGET
    THEN INSERT(STOCKNUMBER,branchID,AUCTIONDATETIME) VALUES(SOURCE.STOCKNUMBER,SOURCE.branchID,SOURCE.AUCTIONDATETIME);
    
truncate table STOCK_stg