//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynData.LKQImage {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRequest", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DynData.LKQImage.ImageUploadRequest))]
    public partial class UserRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DynData.LKQImage.UserInformation UserRequestInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DynData.LKQImage.UserInformation UserRequestInfo {
            get {
                return this.UserRequestInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRequestInfoField, value) != true)) {
                    this.UserRequestInfoField = value;
                    this.RaisePropertyChanged("UserRequestInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInformation", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Entities")]
    [System.SerializableAttribute()]
    public partial class UserInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DynData.LKQImage.AccountNumberBusinessType BusinessTypeForAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        private System.Guid VerificationCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DynData.LKQImage.AccountNumberBusinessType BusinessTypeForAccountNumber {
            get {
                return this.BusinessTypeForAccountNumberField;
            }
            set {
                if ((this.BusinessTypeForAccountNumberField.Equals(value) != true)) {
                    this.BusinessTypeForAccountNumberField = value;
                    this.RaisePropertyChanged("BusinessTypeForAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid VerificationCode {
            get {
                return this.VerificationCodeField;
            }
            set {
                if ((this.VerificationCodeField.Equals(value) != true)) {
                    this.VerificationCodeField = value;
                    this.RaisePropertyChanged("VerificationCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageUploadRequest", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Image.Entities" +
        "")]
    [System.SerializableAttribute()]
    public partial class ImageUploadRequest : DynData.LKQImage.UserRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DynData.LKQImage.ImageInformationDto ImageInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DynData.LKQImage.ImageInformationDto ImageInformation {
            get {
                return this.ImageInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageInformationField, value) != true)) {
                    this.ImageInformationField = value;
                    this.RaisePropertyChanged("ImageInformation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageInformationDto", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Image.Entities" +
        "")]
    [System.SerializableAttribute()]
    public partial class ImageInformationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageByteArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageByteArray {
            get {
                return this.ImageByteArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageByteArrayField, value) != true)) {
                    this.ImageByteArrayField = value;
                    this.RaisePropertyChanged("ImageByteArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockNumber {
            get {
                return this.StockNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StockNumberField, value) != true)) {
                    this.StockNumberField = value;
                    this.RaisePropertyChanged("StockNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountNumberBusinessType", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Entities")]
    public enum AccountNumberBusinessType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aftermarket = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Salvage = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.datacontract.org/2004/07/IntegrationFeatureService.Core.Entity")]
    [System.SerializableAttribute()]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WasSuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasSuccessful {
            get {
                return this.WasSuccessfulField;
            }
            set {
                if ((this.WasSuccessfulField.Equals(value) != true)) {
                    this.WasSuccessfulField = value;
                    this.RaisePropertyChanged("WasSuccessful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LKQCorp.LKQIntegrationService", ConfigurationName="LKQImage.Image")]
    public interface Image {
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Image/UploadImageInformation", ReplyAction="LKQCorp.LKQIntegrationService/Image/UploadImageInformationResponse")]
        DynData.LKQImage.ServiceResult UploadImageInformation(DynData.LKQImage.ImageUploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Image/UploadImageInformation", ReplyAction="LKQCorp.LKQIntegrationService/Image/UploadImageInformationResponse")]
        System.Threading.Tasks.Task<DynData.LKQImage.ServiceResult> UploadImageInformationAsync(DynData.LKQImage.ImageUploadRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImageChannel : DynData.LKQImage.Image, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageClient : System.ServiceModel.ClientBase<DynData.LKQImage.Image>, DynData.LKQImage.Image {
        
        public ImageClient() {
        }
        
        public ImageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DynData.LKQImage.ServiceResult UploadImageInformation(DynData.LKQImage.ImageUploadRequest request) {
            return base.Channel.UploadImageInformation(request);
        }
        
        public System.Threading.Tasks.Task<DynData.LKQImage.ServiceResult> UploadImageInformationAsync(DynData.LKQImage.ImageUploadRequest request) {
            return base.Channel.UploadImageInformationAsync(request);
        }
    }
}
